# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DailyTen' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for DailyTen
  pod 'RNMobileCenter', '~> 0.3.0'
  pod 'MobileCenter', '~> 0.5.0'

  

  target 'DailyTenTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'DailyTen-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for DailyTen-tvOS

  target 'DailyTen-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
